package onboard

import (
	"crypto/rand"
	"encoding/base64"
	"fmt"
	"os"
	"strings"
)

type ConfigTemplateOptions struct {
	SlackEnabled        bool
	SlackDMPolicy       string
	SlackGroupPolicy    string
	SlackRequireMention *bool
	SlackAllowFrom      []string

	FeishuEnabled        bool
	FeishuDMPolicy       string
	FeishuGroupPolicy    string
	FeishuRequireMention *bool
	FeishuAllowFrom      []string

	WorkerType         string
	KeptPlatforms      map[string]bool
	ExistingConfigPath string
}

func DefaultConfigYAML() string {
	return BuildConfigYAML(ConfigTemplateOptions{WorkerType: "claude_code"})
}

func BuildConfigYAML(opts ConfigTemplateOptions) string {
	var b strings.Builder

	b.WriteString(`# HotPlex Worker Gateway - Generated Configuration
# Generated by: hotplex onboard
#
# Sensible defaults for both dev and prod. Override via:
#   1. Inheritance: config-dev.yaml / config-prod.yaml (inherits this file)
#   2. Environment variables: HOTPLEX_* (highest priority)
#   3. Secrets provider: JWT secret, admin tokens (never in config files)
#
# Code defaults live in internal/config/config.go:Default().

`)

	b.WriteString(`# ─────────────────────────────────────────────────────────────────────────────
# CORE NETWORK
# ─────────────────────────────────────────────────────────────────────────────

gateway:
  addr: "localhost:8888"
  ping_interval: 54s
  pong_timeout: 60s
  write_timeout: 10s
  idle_timeout: 5m
  max_frame_size: 32768
  broadcast_queue_size: 256

`)

	b.WriteString(`admin:
  enabled: true
  addr: "localhost:9999"
  rate_limit_enabled: true
  requests_per_sec: 10
  burst: 20

`)

	b.WriteString(`# ─────────────────────────────────────────────────────────────────────────────
# DATA
# ─────────────────────────────────────────────────────────────────────────────

db:
  path: "~/.hotplex/data/hotplex.db"
  wal_mode: true
  busy_timeout: 5s

`)

	b.WriteString(`# ─────────────────────────────────────────────────────────────────────────────
# SECURITY
# ─────────────────────────────────────────────────────────────────────────────

security:
  api_key_header: "X-API-Key"
  tls_enabled: false
  tls_cert_file: "/etc/hotplex/tls/server.crt"
  tls_key_file: "/etc/hotplex/tls/server.key"
  allowed_origins:
    - "*"
  jwt_audience: "hotplex-gateway"

`)

	b.WriteString(`# ─────────────────────────────────────────────────────────────────────────────
# SESSION
# ─────────────────────────────────────────────────────────────────────────────

session:
  retention_period: 168h
  gc_scan_interval: 1m
  max_concurrent: 1000

`)

	b.WriteString(`# ─────────────────────────────────────────────────────────────────────────────
# POOL
# ─────────────────────────────────────────────────────────────────────────────

pool:
  min_size: 0
  max_size: 100
  max_idle_per_user: 5
  max_memory_per_user: 3221225472  # 3GB

`)

	b.WriteString(`# ─────────────────────────────────────────────────────────────────────────────
# WORKER
# ─────────────────────────────────────────────────────────────────────────────

worker:
  max_lifetime: 24h
  idle_timeout: 60m
  execution_timeout: 30m

  auto_retry:
    enabled: true
    max_retries: 9
    base_delay: 5s
    max_delay: 120s
    retry_input: "继续"
    notify_user: true

`)

	b.WriteString(`  # Claude Code worker startup (fork per session)
  claude_code:
    # Command to start Claude Code worker. Default: "claude"
    # To use a custom path, edit here or set HOTPLEX_WORKER_CLAUDE_CODE_COMMAND env var.
    command: "claude"

  # OpenCode Server singleton process (shared across all sessions)
  opencode_server:
    # Command to start OpenCode Server. Default: "opencode"
    # To use a custom path, edit here or set HOTPLEX_WORKER_OPENCODE_SERVER_COMMAND env var.
    command: "opencode"
    idle_drain_period: 30m    # keep process alive 30m after last session
    ready_timeout: 10s        # max wait for server startup
    ready_poll_interval: 200ms
    http_timeout: 30s

`)

	b.WriteString(`# ─────────────────────────────────────────────────────────────────────────────
# LOGGING
# ─────────────────────────────────────────────────────────────────────────────

log:
  level: "info"
  format: "json"

`)

	b.WriteString("# ─────────────────────────────────────────────────────────────────────────────\n")
	b.WriteString("# MESSAGING\n")
	b.WriteString("# ─────────────────────────────────────────────────────────────────────────────\n\n")
	b.WriteString("messaging:\n")

	// Slack — keep existing block or generate fresh
	if !writeKeptPlatform(&b, opts, "slack") {
		writePlatformBlock(&b, "slack", platformBlockOpts{
			Enabled:        opts.SlackEnabled,
			DMPolicy:       defaultStr(opts.SlackDMPolicy, "allowlist"),
			GroupPolicy:    defaultStr(opts.SlackGroupPolicy, "allowlist"),
			RequireMention: defaultBool(opts.SlackRequireMention, true),
			AllowFrom:      opts.SlackAllowFrom,
			Extra:          "    socket_mode: true\n    worker_type: \"claude_code\"\n    stt_provider: \"local\"\n    stt_local_cmd: \"python3 ~/.hotplex/scripts/stt_server.py\"\n    stt_local_idle_ttl: 1h\n",
		})
	}

	// Feishu — keep existing block or generate fresh
	if !writeKeptPlatform(&b, opts, "feishu") {
		writePlatformBlock(&b, "feishu", platformBlockOpts{
			Enabled:        opts.FeishuEnabled,
			DMPolicy:       defaultStr(opts.FeishuDMPolicy, "allowlist"),
			GroupPolicy:    defaultStr(opts.FeishuGroupPolicy, "allowlist"),
			RequireMention: defaultBool(opts.FeishuRequireMention, true),
			AllowFrom:      opts.FeishuAllowFrom,
			Extra:          "    worker_type: \"claude_code\"\n    stt_provider: \"feishu+local\"\n    stt_local_cmd: \"python3 ~/.hotplex/scripts/stt_server.py\"\n    stt_local_idle_ttl: 1h\n",
		})
	}

	b.WriteByte('\n')
	return b.String()
}

type platformBlockOpts struct {
	Enabled        bool
	DMPolicy       string
	GroupPolicy    string
	RequireMention bool
	AllowFrom      []string
	Extra          string
}

func writePlatformBlock(b *strings.Builder, name string, o platformBlockOpts) {
	fmt.Fprintf(b, "  %s:\n    enabled: %t\n", name, o.Enabled)
	b.WriteString(o.Extra)
	fmt.Fprintf(b, "    dm_policy: %q\n    group_policy: %q\n    require_mention: %t\n", o.DMPolicy, o.GroupPolicy, o.RequireMention)
	writeStringList(b, "allow_from", o.AllowFrom)
}

func writeKeptPlatform(b *strings.Builder, opts ConfigTemplateOptions, platform string) bool {
	if !opts.KeptPlatforms[platform] || opts.ExistingConfigPath == "" {
		return false
	}
	block := extractPlatformBlock(opts.ExistingConfigPath, platform)
	if block == "" {
		return false
	}
	b.WriteString(block)
	return true
}

// extractBlock reads the existing config file and extracts the YAML block
// for the given key at the specified indent level. Supports both top-level
// keys (indent="") and nested keys (indent="  " for messaging children).
func extractBlock(configPath, key, indent string) string {
	data, err := os.ReadFile(configPath)
	if err != nil {
		return ""
	}

	lines := strings.Split(string(data), "\n")
	marker := indent + key + ":"

	start := -1
	for i, line := range lines {
		if line == marker || strings.HasPrefix(line, marker+" ") {
			start = i
			break
		}
	}
	if start == -1 {
		return ""
	}

	markerLen := len(indent)
	end := len(lines)
	for i := start + 1; i < len(lines); i++ {
		line := lines[i]
		if line == "" {
			continue
		}
		spaces := 0
		for _, ch := range line {
			if ch == ' ' {
				spaces++
			} else {
				break
			}
		}
		if spaces <= markerLen && line[spaces] != '#' {
			end = i
			break
		}
	}

	return strings.Join(lines[start:end], "\n") + "\n"
}

// extractPlatformBlock reads the existing config file and extracts the YAML block
// for the given platform (e.g., "slack"), preserving custom settings.
func extractPlatformBlock(configPath, platform string) string {
	return extractBlock(configPath, platform, "  ")
}

func writeStringList(b *strings.Builder, key string, items []string) {
	if len(items) == 0 {
		return
	}
	fmt.Fprintf(b, "    %s:\n", key)
	for _, v := range items {
		fmt.Fprintf(b, "      - %s\n", v)
	}
}

func defaultStr(s, def string) string { //nolint:unparam // def varies if more usage added
	if s == "" {
		return def
	}
	return s
}

func defaultBool(p *bool, def bool) bool {
	if p == nil {
		return def
	}
	return *p
}

func GenerateSecret() string {
	// ES256 requires exactly 32 bytes; decodeJWTSecret rejects other lengths.
	b := make([]byte, 32)
	if _, err := rand.Read(b); err != nil {
		panic("crypto/rand.Read failed: " + err.Error())
	}
	return base64.StdEncoding.EncodeToString(b)
}
